### ISSUE TITLE
How about to remove vendor-prefix in SCSS files

### ISSUE THREAD

**Issue by sotayamashita** [designbyjake/sassline#33]
How about to add vendor-prefix during transferring scss to css ? I think it will be more simple

**Comment by designbyjake** [comment]
@sotayamashita With something like Autoprefixer? https://github.com/postcss/autoprefixer

**Comment by sotayamashita** [comment]
@designbyjake Yes it is. What do think ?

Example:

```scss
// scss
selector {
  border-radius: 3px
}
```

↓ Transfer w/ build tool like gulp

```css
// css
selector {
  -webkit-border-radius: 3px
      -moz-border-radius: 3px
               border-radius: 3px
}
```
